### ISSUE TITLE
Unable to crack a hash-list with a username without changing mysql conf

### ISSUE THREAD

**Issue by hegusung** [hegusung/WebHashcat#14]
When using MySQL or MariaDB, secure-file-priv option must be disabled in the configuration file.

```
[mysqld]
secure-file-priv = ""
```

However, It would be better for the code to work without this modification. The destination folder can be found by requesting the secure_file_priv variable in MySQL.

`SHOW VARIABLES LIKE "secure_file_priv";`

**Comment by hegusung** [comment]
WebHashcat/WebHashcat/Files/tmp folder should be writable by mysql for the code to work

**Comment by hegusung** [comment]
AppArmor also prevents MySQL from writing to WebHashcat/WebHashcat/Files/tmp, I should find a way to make it work under such conditions without having to change AppArmor config

**Comment by hegusung** [comment]
Done by writing files via python and not mysql, Might affect performance... 

TODO: make the default to use dump into file, and if not rely on python

**Comment by NBanski** [comment]
Hi! Framework is great and I highly enjoy it. However I have one major issue - my WebHashcat seems to not synchronise properly with server files. Interface doesn't read hashfiles (e.g. there's no information about lines) and I can't delete hashfiles via interface.

I've also added default "--force" option to HashNodes running on virtual machines, so they ran with OpenGL, but I'm still not getting any data back from nodes. Can it be supervisord problem, as I'm not running it at all?
